baseurl = "http://localhost:1313/"
languageCode = "zh-cn"
uglyurls = true
relativeURLs = false
title = "Rust学习笔记"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
preserveTaxonomyNames = true
disablePathToLower = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = "c7442f5794ea2abb71c6ff05dc0b8779"

[params]
# General information
    author = "敖小剑"
    keywords = "rust,学习笔记,敖小剑"
    description = "Rust学习笔记。"
    copyright = "版权所有，转载请注明出处"
    
    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/skyao/learning-rust"
    
    version = ""
    logo = "images/logo.png"
    favicon = ""
    
    permalink = "#"
    
    # reward button, comment this to disable it
    reward = true
    
    # Custom assets
    custom_css = []
    custom_js  = []
    
    # Syntax highlighting theme
    highlight_css  = ""
    
    [params.palette]
    	primary = "red"
    	accent  = "teal"
    
    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "skyao"
	email   = "aoxiaojian@gmail.com"

[[menu.main]]
	name   = "前言"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "介绍"
	identifier = "introduction"
	url    = "/introduction/"
	weight = 100

[[menu.main]]
	name   = "安装"
	identifier = "installation"
	url    = "/installation/"
	weight = 200

[[menu.main]]
	name   = "构建"
	identifier = "build"
	url    = "/build/"
	weight = 250

[[menu.main]]
	name   = "Rustc"
	identifier = "build-rustc"
	parent = "build"
	url    = "/build/rustc/"
	weight = 260

[[menu.main]]
	name   = "Cargo"
	identifier = "build-cargo"
	parent = "build"
	url    = "/build/cargo/"
	weight = 270

[[menu.main]]
	name   = "Lints"
	identifier = "build-lints"
	parent = "build"
	url    = "/build/lints/"
	weight = 280

[[menu.main]]
	name   = "模块"
	identifier = "build-module"
	parent = "build"
	url    = "/build/module/"
	weight = 290

[[menu.main]]
	name   = "语法"
	identifier = "grammar"
	url    = "/grammar/"
	weight = 300

[[menu.main]]
	name   = "基本语法"
	identifier = "grammar-basic"
	parent = "grammar"
	url    = "/grammar/basic/"
	weight = 310

[[menu.main]]
	name   = "数据类型"
	identifier = "grammar-type"
	parent = "grammar"
	url    = "/grammar/type/"
	weight = 320

[[menu.main]]
	name   = "字符串"
	identifier = "grammar-string"
	parent = "grammar"
	url    = "/grammar/string/"
	weight = 340

[[menu.main]]
	name   = "集合"
	identifier = "grammar-collection"
	parent = "grammar"
	url    = "/grammar/collection/"
	weight = 350

[[menu.main]]
	name   = "指针"
	identifier = "grammar-pointer"
	parent = "grammar"
	url    = "/grammar/pointer/"
	weight = 360

[[menu.main]]
	name   = "流程控制"
	identifier = "grammar-flowcontrol"
	parent = "grammar"
	url    = "/grammar/flowcontrol/"
	weight = 370

[[menu.main]]
	name   = "类型系统"
	identifier = "type"
	url    = "/type/"
	weight = 400

[[menu.main]]
	name   = "泛型"
	identifier = "type-generic"
	parent = "type"
	url    = "/type/generic/"
	weight = 420

[[menu.main]]
	name   = "Trait"
	identifier = "type-trait"
	parent = "type"
	url    = "/type/trait/"
	weight = 440

[[menu.main]]
	name   = "类型转换"
	identifier = "type-convert"
	parent = "type"
	url    = "/type/convert/"
	weight = 460

[[menu.main]]
	name   = "所有权"
	identifier = "ownership"
	url    = "/ownership/"
	weight = 1000

[[menu.main]]
	name   = "标准库"
	identifier = "std"
	url    = "/std/"
	weight = 2000

[[menu.main]]
	name   = "集合"
	identifier = "std-collections"
	parent = "std"
	url    = "/std/collections/"
	weight = 2010

[[menu.main]]
	name   = "同步"
	identifier = "std-sync"
	parent = "std"
	url    = "/std/sync/"
	weight = 2030

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


